### ISSUE TITLE
Prebuilt binaries

### ISSUE THREAD

**Issue by Avamander** [foxcpp/maddy#126]
# Use case

Easier installation

Many distributions ship old versions of go, building maddy is often tedious

# Your idea for a solution

Have a prebuilt binary available under GitHub's `releases` for a few common distributions

**Comment by foxcpp** [comment]
>Many distributions ship old versions of go, building maddy is often tedious

It is easy to install a newer Go version using the distribution-shipped version:
```
go get golang.org/dl/go1.12.9
go1.12.9 download
```

Then you can use `go1.12.9` instead of `go` to build maddy.

>Have a prebuilt binary available under GitHub's releases for a few common distributions

There will be prebuilt binaries for [maddy 0.1](https://github.com/foxcpp/maddy/milestone/1) and other releases.
Side note: There is no need to provide binaries for different distributions, maddy does not depend on system libraries (other than libc for SQLite3, but it can be linked statically).

**Comment by Avamander** [comment]
`go get golang.org/dl/go1.12.9` huh, thanks for letting me (and probably others coming from Google) know this is possible. However I still think some would love just wget-ing the binary and using that.

**Comment by foxcpp** [comment]
Another note: Since glibc cannot be linked statically and it is not possible to create a portable binary linking glibc dynamically (it will depend on a specific glibc version), maddy release builds will be linked statically with musl-libc. This also means that release builds will not include the support for PAM integration.

I think the build will be produced using `./build.sh package` with a compiler wrapper to use musl-libc and custom set of flags to produce completely static binary.

**Comment by foxcpp** [comment]
Threw together some automation for reproductive pre-built binaries building. ATM it is Alpine Linux 3.11.3, GCC 9.1, some musl-libc and Go 1.13.4.
All resources used are there: https://foxcpp.dev/maddy-repro/. Along with the script that builds what I will attach to the actual release. Given the same binaries as provided at the link above, it should produce the bit-perfect copy of the archive or at least executables.

Either way, I think it is more than simple to build the maddy from source too. `curl https://foxcpp.dev/maddy/build.sh| bash`

Soo... I think we can consider this issue resolved?
