### ISSUE TITLE
Starting maddy: open \: no such file or directory

### ISSUE THREAD

**Issue by onny** [foxcpp/maddy#159]
Hey I'm using the latest maddy version from git master r607.1bc7036 and also updated my package on the AUR: https://aur.archlinux.org/packages/maddy-git
After removing /var/lib/maddy and setting hostname and primary domain to "something.com" in maddy.conf I get following error when starting the systemd service: open \: no such file or directory

Unfortunately I couldn't it debug it any further.

Best regards,
Jonas

**Comment by foxcpp** [comment]
Can't get that exact error message (with missing path), but installing your AUR package gives me this:
```
maddy[239880]: open /etc/maddy/certs/something.com/fullchain.pem: no such file or directory
```
This is expected since TLS configuration is [left to the user](https://github.com/foxcpp/maddy/wiki/Tutorial:-Setting-up-a-mail-server-with-maddy#tls-certificates), default values are merely placeholders (convenient ones, though, if you use certbot).

--

Though that backslash gives me some ideas that configuration lexer may improperly handle that trailing `\` to continue the directive on the next line. Can you try it with both paths on the same line (removing `\`)?
```
tls /etc/maddy/certs/$(hostname)/fullchain.pem /etc/maddy/certs/$(hostname)/privkey.pem
```

**Comment by onny** [comment]
Yep now it works, thanks for the hint!

**Comment by foxcpp** [comment]
I am still interested in the cause of this problem, though. If you still have the configuration that reproduces it - can you upload it somewhere? (there may be something weird with whitespace or line endings or something else, so don't use pastebin-like services).

**Comment by onny** [comment]
I get this issue using the latest maddy.conf from git. Here is the file which causes the error https://onny.project-insanity.org/files/maddy.conf

**Comment by foxcpp** [comment]
Ah, silly me. I thought config/parser supports that use of `\` but apparently it doesn't (when testing I kept replacing these paths with `tls self_signed` since I don't have certs there).
