### ISSUE TITLE
Milter protocol support

### ISSUE THREAD

**Issue by emersion** [foxcpp/maddy#16]
There could be several filter backends. One of them could be https://github.com/emersion/go-milter

**Comment by foxcpp** [comment]
We have generic filtering support in, but itis basically useless without any filters so I don't consider the "email filters support" issue to be resolved. For this reason, I renamed this issue to "Milter protocol support" because milter is widely adopted protocol used for external filters (spam filters, antiviruses, etc).

**Comment by foxcpp** [comment]
Ref. https://github.com/emersion/go-milter/issues/3
Ref. https://github.com/emersion/go-milter/pull/6

**Comment by foxcpp** [comment]
Experimental milter protocol client implementation is in development tree. Pending for 0.3.
