### ISSUE TITLE
Easy to use catch all email address

### ISSUE THREAD

**Issue by daniel-naegele** [foxcpp/maddy#243]
# Use case

What problem you are trying to solve?
I would like to have a catch-all email address. This could be useful for example to use different email addresses for different websites e.g. `amazon@example.org`, `github@example.org`. This could prevent spam from single sites, as you could create another account after you receive too much emails from one service.

# Your idea for a solution

Either via the maddyctl: `maddyctl creds create *@example.org`
Or the configuration file, where you could choose between different policies like `reject` or `catch-all *@example.org`

- [ ] I'm willing to help with the implementation

**Comment by foxcpp** [comment]
Probably not exactly "easy" but there is a way already using destination_in and address rewriting, described in [maddy-storage(5)](https://foxcpp.dev/maddy/man/_generated_maddy-storage.5). There is a typo in config example though... That needs to be fixed.

```
destination_in &local_mailboxes {
    deliver_to &local_mailboxes
}
destination example.org {
    modify {
        replace_rcpt regexp ".*" "catchall@example.org"
    }
    deliver_to &local_mailboxes
}
```
The logic in this configuration snippet is as follows: `destination_in` takes priority over `destination`, `imapsql` module can be used with `destination_in` acting as a list of existing IMAP accounts and `modify` block with `replace_rcpt` turns recipients for other addresses on a domain into catchall@example.org.

Note that I am not sure I want to make it easier since catch-alls are rarely a good idea - spammers frequently probe a lot of common addresses and you risk getting considerably more spam this way. Recommended approach for your use-case is to use prefixes with address rewriting, such as `butzlabben+github@example.org` being delivered to `butzlabben@example.org`. In fact, it is already implemented in default configuration: https://github.com/foxcpp/maddy/blob/master/maddy.conf#L102

**Comment by daniel-naegele** [comment]
Thank you for this extensively answer. Considering all the facts, I think I can close this issue now.

Keep up the good work.

**Comment by arisudesu** [comment]
The issue is a bit outdated, though it has to be mentioned that configuration above prevents delivering to correct local mailboxes when rcpt contains plus-tag.

E.g have local mailboxes catchall@example.com, personal@example.com. Mail sent to personal@example.com lands in personal@example.com mailbox as it should be, whereas personal+tag@example.com lands in catchall@example.com mailbox. Technically this is correct behavior, but it may not be common sense for everyone.

It may be resolved if modify {} block is applied before trying to deliver to destination_in:
```
# unchanged from defaults
table.chain local_rewrites {
    optional_step regexp "(.+)\+(.+)@(.+)" "$1@$3"
    optional_step static {
        entry postmaster postmaster@$(primary_domain)
    }
    optional_step file /etc/maddy/aliases
}

msgpipeline local_routing {
    modify {
        replace_rcpt &local_rewrites
    }

    # at this point rcpt was normalized to either:
    #       postmaster@$(primary_domain),
    #       local_mailbox_without_tag@$(local_domains),
    #       replacements with alias

    # destination_in block takes priority over destinations
    destination_in &local_mailboxes {
        deliver_to &local_mailboxes
    }

    # if rcpt is not in local_mailboxes, but has our domains,
    # replace rcpt to catchall and deliver it there
    destination $(local_domains) {
        modify {
            replace_rcpt regexp ".*" "catchall@$(primary_domain)"
        }
        deliver_to &local_mailboxes
    }

    default_destination {
        reject 550 5.1.1 "User doesn't exist"
    }
}

```
Now, mail sent to personal+tag@example.com lands in personal@example.com mailbox.

Should I be wrong, correct me, please.

**Comment by altdsoy** [comment]
> Now, mail sent to [personal+tag@example.com](mailto:personal+tag@example.com) lands in [personal@example.com](mailto:personal@example.com) mailbox.

Hello @arisudesu , is it possible to customize the "+ addressing" character?
E.g. I would like to use `-` instead of `+` which is often not recognized as valid on some websites.

I'm trying to self host a mail server for the exact same use case described here..
Come here from this link: https://vadosware.io/post/its-never-been-easier-or-harder-to-self-host-email/

I laughed when I read "You don’t have to postfix + dovecot in 2022.".

Hopefully I'll be able to start my self hosting email journey with maddy :)

**Comment by taoso** [comment]
Hi @altdsoy this is the default local rewrite rules for incoming email.
```
table.chain local_rewrites {
    optional_step regexp "(.+)\+(.+)@(.+)" "$1@$3"
    optional_step static {
        entry postmaster postmaster@$(primary_domain)
    }
    optional_step file /etc/maddy/aliases
}
```

The second line of `optional_step regexp "(.+)\+(.+)@(.+)" "$1@$3"` means treating receiver address of `foo+bar@example.com` as `foo@example.com`. You can see the `\+` in the regular expression.

If you prefer `-`, you may change the above line to `optional_step regexp "(.+)-(.+)@(.+)" "$1@$3"`. So all emails sending to `foo-bar@example.com` will be delivered to `foo@example.com`.
