### ISSUE TITLE
Queue module is not usable on Windows

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/maddy#334]
Method updateMetadataOnDisk tries to move metadata file while it is open. Also, os.Rename is used to replace previous file (if any).

**Comment by foxcpp** [comment]
I believe the referenced commit fixes it. Could anyone confirm?

**Comment by rawtaz** [comment]
FWIW I was the one who initially reported the problem, and today I ran the as-of-writing-this master@5eec45e and am no longer seeing this issue. I've only done a couple of test mails though, but I see maddy accepting them and then retrying the queue as well when they can't be delivered due to other network problems. Seems you can close this.
